from dotenv import load_dotenv
load_dotenv()

"""
report_writer.py
----------------
The HANDS of the data-incident-agent.

Takes the structured incident report produced by agent.py (the Brain)
and persists it in two places:
  1. Local JSON file  — for immediate human review / debugging
  2. Databricks Delta table — for historical trending, dashboards, and audit trail

Why both?
  - File: zero-friction, always readable, great for CLI dev workflow
  - Delta table: incident reports ARE data — store them like data engineers do.
    Over time this table becomes a historical record:
    "How often does bronze_orders_stream go stale? Is it getting worse?"
    That's observability you can query, chart, and alert on.
"""

import os
import json
import requests
import time
from datetime import datetime, timezone
from databricks.sdk import WorkspaceClient

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------

REPORT_DIR = "reports"
DELTA_TABLE = "workspace.ecommerce.incident_reports"


# ---------------------------------------------------------------------------
# Databricks helpers (reuse same pattern as collect_metrics.py)
# ---------------------------------------------------------------------------

def _get_client():
    return WorkspaceClient()


def _get_warehouse_id(client) -> str:
    http_path = os.environ.get("DATABRICKS_HTTP_PATH", "")
    if http_path:
        return http_path.strip("/").split("/")[-1]
    warehouses = client.warehouses.list()
    for wh in warehouses:
        if wh.state.value in ("RUNNING", "IDLE"):
            return wh.id
    raise RuntimeError("No running SQL warehouse found.")


def _execute_sql(client, sql: str, warehouse_id: str):
    host = client.config.host
    token = client.config.token
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
    }
    resp = requests.post(
        f"{host}/api/2.0/sql/statements",
        headers=headers,
        json={
            "statement": sql,
            "warehouse_id": warehouse_id,
            "wait_timeout": "30s",
            "on_wait_timeout": "CONTINUE",
        },
    )
    resp.raise_for_status()
    payload = resp.json()
    statement_id = payload["statement_id"]

    for _ in range(30):
        state = payload.get("status", {}).get("state", "")
        if state in ("SUCCEEDED", "FAILED", "CANCELED", "CLOSED"):
            break
        time.sleep(2)
        poll = requests.get(
            f"{host}/api/2.0/sql/statements/{statement_id}",
            headers=headers,
        )
        poll.raise_for_status()
        payload = poll.json()

    state = payload.get("status", {}).get("state")
    if state != "SUCCEEDED":
        error = payload.get("status", {}).get("error", {})
        raise RuntimeError(f"SQL failed [{state}]: {error.get('message', 'unknown')}")


# ---------------------------------------------------------------------------
# Writer 1 — Local JSON file
# ---------------------------------------------------------------------------

def write_to_file(report: dict) -> str:
    """
    Write the incident report to a timestamped JSON file in /reports.
    Returns the file path written.
    """
    os.makedirs(REPORT_DIR, exist_ok=True)

    run_id = report.get("run_id", f"incident-{datetime.now(timezone.utc).strftime('%Y%m%d-%H%M%S')}")
    filename = f"{REPORT_DIR}/{run_id}.json"

    with open(filename, "w") as f:
        json.dump(report, f, indent=2)

    print(f"   📄 Report written to file: {filename}")
    return filename


# ---------------------------------------------------------------------------
# Writer 2 — Databricks Delta table
# ---------------------------------------------------------------------------

def _ensure_table_exists(client, warehouse_id: str):
    """
    Create the incident_reports Delta table if it doesn't already exist.
    Each row = one agent run. Incidents stored as JSON string for flexibility.
    """
    sql = f"""
    CREATE TABLE IF NOT EXISTS {DELTA_TABLE} (
        run_id              STRING,
        generated_at        TIMESTAMP,
        severity            STRING,
        incident_count      INT,
        overall_health      STRING,
        incidents_json      STRING,
        immediate_actions   STRING,
        tables_monitored    INT,
        metrics_collected_at TIMESTAMP
    )
    USING DELTA
    COMMENT 'Incident reports generated by data-incident-agent. Each row is one agent run.'
    """
    _execute_sql(client, sql.strip(), warehouse_id)
    print(f"   ✅ Delta table ready: {DELTA_TABLE}")


def write_to_delta(report: dict):
    """
    Insert the incident report as a single row into the Delta table.
    Incidents and immediate_actions stored as JSON strings for queryability.
    """
    print(f"   🔌 Connecting to Databricks Delta...")
    client = _get_client()
    warehouse_id = _get_warehouse_id(client)

    _ensure_table_exists(client, warehouse_id)

    # Safely escape single quotes in JSON strings
    def esc(val):
        return str(val).replace("'", "\\'")

    incidents_json = esc(json.dumps(report.get("incidents", [])))
    immediate_actions = esc(json.dumps(report.get("immediate_actions", [])))
    overall_health = esc(report.get("overall_health", ""))

    # Handle timestamp formatting
    generated_at = report.get("generated_at", datetime.now(timezone.utc).isoformat())
    metrics_collected_at = report.get("metrics_collected_at", datetime.now(timezone.utc).isoformat())

    # Trim to valid timestamp format for Delta
    generated_at = generated_at[:19].replace("T", " ")
    metrics_collected_at = metrics_collected_at[:19].replace("T", " ")

    sql = f"""
    INSERT INTO {DELTA_TABLE} VALUES (
        '{report.get("run_id")}',
        TIMESTAMP '{generated_at}',
        '{report.get("severity", "UNKNOWN")}',
        {report.get("incident_count", 0)},
        '{overall_health}',
        '{incidents_json}',
        '{immediate_actions}',
        {report.get("tables_monitored", 0)},
        TIMESTAMP '{metrics_collected_at}'
    )
    """
    _execute_sql(client, sql.strip(), warehouse_id)
    print(f"   ✅ Report inserted into Delta table: {DELTA_TABLE}")


# ---------------------------------------------------------------------------
# Main entry point
# ---------------------------------------------------------------------------

def write_report(report: dict):
    """
    Persist the incident report to both destinations.
    Called by run_agent.py after the agentic loop completes.
    """
    print("\n✍️  Writing incident report...")

    # 1. Local file — always written first, never fails silently
    file_path = write_to_file(report)

    # 2. Delta table — data engineers store reports as data
    try:
        write_to_delta(report)
    except Exception as e:
        print(f"   ⚠️  Delta write failed (file report still saved): {e}")

    print(f"\n✅ Report persisted successfully.")
    print(f"   Severity     : {report.get('severity')}")
    print(f"   Incidents    : {report.get('incident_count', 0)}")
    print(f"   File         : {file_path}")
    print(f"   Delta table  : {DELTA_TABLE}")


if __name__ == "__main__":
    # Quick test — write a dummy report to verify both destinations work
    dummy_report = {
        "run_id": "incident-test-001",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "severity": "LOW",
        "incident_count": 1,
        "overall_health": "Test run — all systems nominal.",
        "incidents": [
            {
                "table": "bronze_orders_stream",
                "layer": "bronze",
                "severity": "LOW",
                "observation": "Test observation",
                "likely_cause": "Test cause",
                "recommended_action": "Test action"
            }
        ],
        "immediate_actions": ["This is a test run"],
        "tables_monitored": 14,
        "metrics_collected_at": datetime.now(timezone.utc).isoformat(),
    }
    write_report(dummy_report)
